name: financo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  google_sign_in: ^7.2.0
  purchases_flutter: ^9.10.6
  purchases_ui_flutter: ^9.10.6
  supabase_flutter: ^2.12.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env
