name: financo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  google_sign_in: ^7.2.0
  purchases_flutter: ^9.10.7
  purchases_ui_flutter: ^9.10.7
  supabase_flutter: ^2.12.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  go_router: ^14.6.2
  flutter_svg: ^2.2.2
  flutter_animate: ^4.5.2
  vector_math: ^2.2.0
  plaid_flutter: ^5.0.5
  syncfusion_flutter_maps: ^32.1.25
  fl_chart: ^1.1.1
  country_picker: ^2.0.26
  intl: ^0.20.2
  rrule: ^0.2.15
  genui_firebase_ai: ^0.6.1
  genui: ^0.6.1
  json_schema_builder: ^0.1.3
  lottie: ^3.3.2
  local_auth: ^3.0.0
  shared_preferences: ^2.5.4
  connectivity_plus: ^7.0.0  
  internet_connection_checker_plus: ^2.9.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - .env
    - assets/world_map.json

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-Light.ttf
          weight: 300