name: financo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  brick_core: ^2.0.0
  brick_offline_first: ^4.0.1
  brick_offline_first_with_supabase: ^2.1.0
  brick_sqlite: ^4.1.0
  brick_supabase: ^2.1.0
  connectivity_plus: ^7.0.0
  country_state_city: ^0.1.6
  dartz: ^0.10.1
  dotted_border: ^3.1.0
  equatable: ^2.0.7
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_dotenv: ^6.0.0
  flutter_localization: ^0.3.0
  flutter_secure_storage: ^9.2.3
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^16.0.0
  google_sign_in: ^7.1.1
  intl: ^0.20.2
  intl_utils: ^2.8.8
  loading_animation_widget: ^1.3.0
  mockito: ^5.4.5
  multi_dropdown: ^3.0.1
  pinput: ^5.0.1
  shared_preferences: ^2.3.5
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.4.1
  sqflite_common: ^2.5.4+6
  supabase_flutter: ^2.8.3
  timeago: ^3.7.0
  uuid: ^4.5.1
  custom_country_state_city:
    git:
      url: https://github.com/youngyouth22/custom_country_state_city
      ref: main
  shimmer: ^3.0.0
  gradient_borders: ^1.0.1
  leak_tracker: ^11.0.2
  flutter_animate: ^4.5.2
  faker: ^2.2.0
  vector_math: ^2.2.0
  scrollable_positioned_list: ^0.3.8
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  brick_offline_first_with_supabase_build: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
